# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-22 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20180921_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='podcast_file',
            new_name='material_file',
        ),
    ]
